### ISSUE TITLE
Error when train RNTN sentiment Model

### ISSUE THREAD

**Issue by liybu36** [smoothnlp/SmoothNLP#2]
I have a train ready corpus. However, when trying to train a sentiment model with code provided in the tutorial. It gives Exception as follows:
![image](https://user-images.githubusercontent.com/8764562/52786083-dcd8ce80-3094-11e9-90f5-e2e29e5c3b8a.png)

**Comment by zhangruinan** [comment]
The error is caused when your label(y), sentimental score has a value larger than 4. Check your train dataset, make sure all your labels are smaller than 5. 

Alternatively, you may add following args during training 
```
-numClasses 6 -classNames "Very negative,Negative,Neutral,Positive,Very positive,Unknown" 
```
