### ISSUE TITLE
请问计算score而构造的统计量有什么依据么？

### ISSUE THREAD

**Issue by shenxuhui** [smoothnlp/SmoothNLP#31]
特别是 左右信息熵的 组合

**Comment by Yvette-Wang** [comment]
词语内聚程度：由于PMI的值会受到候选词长度的影响（候选词越长，互信息取值偏大），因此最终选择了平均互信息(AMI)
<img width="296" alt="PMI" src="https://user-images.githubusercontent.com/46989614/72677573-c921bd80-3ad8-11ea-8d5a-a5290bef444d.PNG">

左右邻字丰富程度：比较常见的方法如HanLP使用的BE=min(左熵,右熵)。然而，存在一些BE无法解决的case。如：“在朋友圈”有BE=min(7.71,6.09)=6.09，“美图秀秀”有BE=min(6.09,6.29)=6.09。“在朋友圈”这类词汇，虽然不是严格意义上的短语，但是属于中文的常用表达，因此有较高的BE和AMI。它们唯一的弱点就是，左右某侧的表达会相对固定，因此 左右熵的差(|LE-RE|) 比一般的短语更大。因此我们在度量左右邻字丰富程度的时候，综合考虑了LE,RE,|LE-RE|。

**Comment by shenxuhui** [comment]
好想法！那请问句首的左信息熵和句尾的右信息熵，是如何计算的呢？

**Comment by shenxuhui** [comment]
> 词语内聚程度：由于PMI的值会受到候选词长度的影响（候选词越长，互信息取值偏大），因此最终选择了平均互信息(AMI)
> <img alt="PMI" width="296" src="https://user-images.githubusercontent.com/46989614/72677573-c921bd80-3ad8-11ea-8d5a-a5290bef444d.PNG">
> 
> 左右邻字丰富程度：比较常见的方法如HanLP使用的BE=min(左熵,右熵)。然而，存在一些BE无法解决的case。如：“在朋友圈”有BE=min(7.71,6.09)=6.09，“美图秀秀”有BE=min(6.09,6.29)=6.09。“在朋友圈”这类词汇，虽然不是严格意义上的短语，但是属于中文的常用表达，因此有较高的BE和AMI。它们唯一的弱点就是，左右某侧的表达会相对固定，因此 左右熵的差(|LE-RE|) 比一般的短语更大。因此我们在度量左右邻字丰富程度的时候，综合考虑了LE,RE,|LE-RE|。

好想法！那请问句首的左信息熵和句尾的右信息熵，是如何计算的呢？

**Comment by shenxuhui** [comment]
委书记 20.24616157846446 6.74872052615482 1.4384876329154261 1.4447738350294779 1.4384876329154261 11.809369935814551
党委书记 34.30240580918637 8.575601452296592 0.0 0.0 0.0 -19.818766484041273
县委书记 29.48672936288092 7.37168234072023 0 0 0 -21.022685595617634
省委书记 27.68915328791832 6.92228832197958 0 0.0 0 -21.472079614358286

以上例子的左右信息熵不太符合预期。
