### ISSUE TITLE
阅读源码后的两个疑问

### ISSUE THREAD

**Issue by shenxuhui** [smoothnlp/SmoothNLP#32]
疑问1：
## DONE 对在candidate ngram中, 首字或者尾字出现次数特别多的进行筛选, 如"XX的,美丽的,漂亮的"剔出字典
    target_ngrams = word_info_scores.keys()
    start_chars = Counter([n[0] for n in target_ngrams])
    end_chars = Counter([n[-1] for n in target_ngrams])
    threshold = min(2000, int(len(target_ngrams) * 0.001))
    threshold = max(50, threshold)
    logger.info("~~~ Threshold used for removing start end char: {} ~~~~".format(threshold))
    invalid_start_chars = set([char for char, count in start_chars.items() if count > threshold])
    invalid_end_chars = set([char for char, count in end_chars.items() if count > threshold])

    invalid_target_ngrams = set([n for n in target_ngrams if (n[0] in invalid_start_chars or n[-1] in invalid_end_chars)])

    for n in invalid_target_ngrams:  ## 按照不合适的字头字尾信息删除一些
        word_info_scores.pop(n)

请问增加该方法是出于怎样的考量？简单做了实验发现过滤停用词也可以达到类似效果，但是没有做太多实验。

**Comment by Yvette-Wang** [comment]
根据我的理解，你说的 “过滤停用词” 是过滤以 “的、等、他” 这样的字为开头/结尾的词吧。不同的文本抽取出的target_ngram不同，所以我们认为，在target_ngram首/尾出现次数过多的char，可以被认为是这份target_ngram中的“停用词”。那么我们方法可以看作 根据不同语料过滤不同的停用词，能够避免一些错误的过滤。

**Comment by shenxuhui** [comment]
> 根据我的理解，你说的 “过滤停用词” 是过滤以 “的、等、他” 这样的字为开头/结尾的词吧。不同的文本抽取出的target_ngram不同，所以我们认为，在target_ngram首/尾出现次数过多的char，可以被认为是这份target_ngram中的“停用词”。那么我们方法可以看作 根据不同语料过滤不同的停用词，能够避免一些错误的过滤。

小数据量会误删一部分词，比如随机抽取 36kr 10000 句做新词发现，字节跳动这个词就被过滤了。

**Comment by Yvette-Wang** [comment]
这里给出的方法更适用于基于大规模语料的新词发现。如果希望小数据量有较好的效果，需要调整代码中的threshold，或者选择直接过滤停用词词典。

**Comment by shenxuhui** [comment]
> 这里给出的方法更适用于基于大规模语料的新词发现。如果希望小数据量有较好的效果，需要调整代码中的threshold，或者选择直接过滤停用词词典。

建议这个方法在 readme 说明下，感觉同类新词发现，你们项目的性能很依赖这个方法。

**Comment by Yvette-Wang** [comment]
感谢建议！无监督的新词发现方法，在小数据量上也很难有好的效果。我们选择这个方法也是希望能够根据不同的 文本及文本量 决定需要过滤的词，减少新词发现结果的标注成本。我们会在代码中添加相关注释~

**Comment by shenxuhui** [comment]
> 感谢建议！无监督的新词发现方法，在小数据量上也很难有好的效果。我们选择这个方法也是希望能够根据不同的 文本及文本量 决定需要过滤的词，减少新词发现结果的标注成本。我们会在代码中添加相关注释~

给你们看个结果，数据是 36kr 一季度的新闻 37 万句。绿色是被该方法过滤了的词。
![Screenshot from 2020-02-17 09-44-17](https://user-images.githubusercontent.com/8621166/74617878-5acd2b00-516a-11ea-9b31-cf4e92143311.png)

**Comment by shenxuhui** [comment]
![Screenshot from 2020-02-17 09-49-51](https://user-images.githubusercontent.com/8621166/74617986-e0e97180-516a-11ea-905c-f148935065b9.png)
