### ISSUE TITLE
pip install SmoothNLP failed

### ISSUE THREAD

**Issue by BigICicle** [smoothnlp/SmoothNLP#45]
(pyEnv37) C:\Users\********>pip install smoothNlp
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting smoothNlp
  Downloading https://mirrors.aliyun.com/pypi/packages/5e/64/e9d7e18e51a5ae3f7c3a6791d862cbbf65a8cb3ecaaee281b0e96eccca2b/SmoothNLP-0.3.1.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\********\wwwFlask\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\********\\AppData\\Local\\Temp\\pip-install-5exu66t9\\smoothNlp\\setup.py'"'"'; __file__='"'"'C:\\Users\\********\\AppData\\Local\\Temp\\pip-install-5exu66t9\\smoothNlp\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\********\AppData\Local\Temp\pip-install-5exu66t9\smoothNlp\pip-egg-info'
         cwd: C:\Users\********\AppData\Local\Temp\pip-install-5exu66t9\smoothNlp\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\********\AppData\Local\Temp\pip-install-5exu66t9\smoothNlp\setup.py", line 5, in <module>
        long_description = open(os.path.join(rootdir, 'README.md')).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 690: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by zhangruinan** [comment]
smoothnlp上传到pypi的安装包，默认的README.md默认编码是utf-8；您的环境默认编码是gbk； 所以导致编码失败。 建议可以考虑 git clone 项目， 然后进行 `python setup.py install`来进行源码编译。

**Comment by zhangruinan** [comment]
该问题已在0.3.4版本中fix
