### ISSUE TITLE
【新词发现】处理数据bug

### ISSUE THREAD

**Issue by gcbanana** [smoothnlp/SmoothNLP#46]
当corpus的类型为list时，为了避免空字符串出现，应该是len(remove_irregular_chars(sent)) != 0

**Comment by Yvette-Wang** [comment]
感谢您的反馈，已修正

**Comment by gcbanana** [comment]
还有一个小问题，还是新词发现中，最后你们用左右熵来构造指标的时候，log的底选择了1.5而不是2，这里有什么讲究么，还是实验发现这个参数比较好
